var friendsinfo=[
    {username:'冰蓝',imgurl:require('./images/ChatHeads/id1.jpg'),id:1},
    {username:'f8',imgurl:require('./images/ChatHeads/id2.jpg'),id:2},
    {username:'教练',imgurl:require('./images/ChatHeads/id3.jpg'),id:3},
    {username:'仅是合',imgurl:require('./images/ChatHeads/id4.jpg'),id:4},
    {username:'淋着',imgurl:require('./images/ChatHeads/id5.jpg'),id:5},
    {username:'Minco',imgurl:require('./images/ChatHeads/id6.jpg'),id:6},
    {username:'潘越',imgurl:require('./images/ChatHeads/id7.jpg'),id:7},
    {username:'琴141',imgurl:require('./images/ChatHeads/id8.jpg'),id:8},
    {username:'生生',imgurl:require('./images/ChatHeads/id9.jpg'),id:9},
    {username:'tangjie',imgurl:require('./images/ChatHeads/id10.jpg'),id:10},
    {username:'杨一',imgurl:require('./images/ChatHeads/id11.jpg'),id:11},
    {username:'应该有天堂',imgurl:require('./images/ChatHeads/id12.jpg'),id:12},
    {username:'乐斗仔仔',imgurl:require('./images/ChatHeads/id13.jpg'),id:13},
    {username:'张鑫',imgurl:require('./images/ChatHeads/id14.jpg'),id:14},
    {username:'左右',imgurl:require('./images/ChatHeads/id15.jpg'),id:15},
    {username:'元气',imgurl:require('./images/ChatHeads/id16.jpg'),id:16},
    {username:'李沅君',imgurl:require('./images/ChatHeads/id17.jpg'),id:17},
    {username:'力元君',imgurl:require('./images/ChatHeads/id18.jpg'),id:18},
    {username:'四季萌芽',imgurl:require('./images/ChatHeads/id19.jpg'),id:19},
    {username:'阿刁',imgurl:require('./images/ChatHeads/id20.jpg'),id:20},
    {username:'藤原拓海',imgurl:require('./images/ChatHeads/id21.jpg'),id:21},
    {username:'夏树',imgurl:require('./images/ChatHeads/id22.jpg'),id:22},
    {username:'AE86',imgurl:require('./images/ChatHeads/id23.jpg'),id:23}
]
export default friendsinfo